### ISSUE TITLE
Ignorelist of BSSIDs for alterting - either just for deauth or all alerts

### ISSUE THREAD

**Issue by MrButlerTron** [nzymedefense/nzyme#811]
Nzyme currently alerts on deauth floods and offers the ability to tune how many deauths are considered a flood.  In crowded urban environments or multi-tenant facilities nzyme may see deauths from devices that are just performing poorly/malfunctioning.  

Increasing the deauth flood thresh hold is the current way to handle these, but if the deauth is not directed at one of your BSSIDs you risk not seeing quieter attackers do to a nearby system out of your control.

It would be great to have a [ignore] list of BSSIDs for which I don't want deauth flood alerts (or maybe any alerts - I could go either way).  That way if a nearby router/client is performing poorly/malfunctioning, but is outside my control I don't have to set the deauth flood level to something larger.

Thanks for everything, love the product as is.  Let me know if you have questions or this needs clarification.

**Comment by lennartkoopmann** [comment]
Hi,

thanks for the suggestion! We discussed it internally and came to the conclusion that v2.0.0 will allow this through the new way of how monitored networks work. Deauthentication-related alerts for a specific BSSID/network will only be issued if the network is monitored.

You can think of it as an allowlist instead of an ignorelist. Hope that makes sense!
