### ISSUE TITLE
Lora Hat

### ISSUE THREAD

**Issue by shandshellin** [nzymedefense/nzyme#819]
I have the tracker working with usb lora but i coul duse some help gettting the lora hat working via spi with it mounted on the gpio. Is there any info on how to do this?

**Comment by MrButlerTron** [comment]
1) Did it work over USB?

2) Did you adjust the jumpers based on the documentation to indicate that you were controlling it via the Pi directly instead of over USB?   Number 10 in the hardware description.
[https://www.waveshare.com/wiki/SX1262_868M_LoRa_HAT#Hardware_description](https://www.waveshare.com/wiki/SX1262_868M_LoRa_HAT#Hardware_description)

**Comment by shandshellin** [comment]
Works fine over usb, i adjusted the jumpers according to the doc but no dice.

**Comment by shandshellin** [comment]
WHat would i need to tchange int he config for the lora device instead of USB001 what would the name of the com port be?
